services:

    Dontdrinkandroot\ApiPlatformBundle\Serializer\GroupsAndAttributesContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments:
            - '@Dontdrinkandroot\ApiPlatformBundle\Serializer\GroupsAndAttributesContextBuilder.inner'
            - !tagged_iterator ddr_api_platform.groups_mapper
            - !tagged_iterator ddr_api_platform.attributes_mapper
        autoconfigure: false

    Dontdrinkandroot\ApiPlatformBundle\Serializer\Group\OperationGroupsMapper:
        arguments:
            $enabled: '%ddr_api_platform.serializer.operation_groups_enabled%'
        tags: [ 'ddr_api_platform.attributes_mapper' ]
