name: "Continuous Integration"

on:
    push:
        branches: [ master ]

env:
    fail-fast: true

jobs:
    phpunit:
        name: "PHPUnit"
        runs-on: "ubuntu-20.04"
        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v2"
            -   name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "7.4"
                    coverage: "pcov"
                    ini-values: "zend.assertions=1"
            -   name: "Install dependencies with Composer"
                uses: "ramsey/composer-install@v1"
            -   name: "Run PHPUnit"
                run: "vendor/bin/phpunit"
